setw -g mode-keys vi

set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

set -g status-style 'bg=#333333 fg=#5eacd3'
set -g status-right '#H'

# fix nvim colours
set-option -a terminal-features 'xterm-256color:RGB'
