# Backend
backend = "glx";
vsync = true;

# Basic settings
shadow = false;
fading = false;
inactive-opacity = 1.0;
active-opacity = 1.0;
opacity-rule = [ "100:class_g = '.*'" ];

# Enable per-pixel transparency
use-damage = true;
