keep-open=yes
load-unsafe-playlists=yes
ytdl-format=bestvideo[height<=?1440][fps<=?60]+bestaudio/best

[youtube]
profile-desc="profile for YouTube videos"
profile-cond=get("path",""):find('youtu%.?be')
profile-restore=copy
deband=yes
volume=60
ytdl-raw-options="playlist-reverse=,cookies-from-browser=firefox,"

[protocol.https]
cache=yes
cache-secs=9999
demuxer-max-bytes=2GiB
demuxer-max-back-bytes=1GiB

[protocol.http]
profile=protocol.https
