# Streams
load-unsafe-playlists=yes
ytdl-format=bestvideo[height<=1440]+bestaudio/best[height<=1440]
ytdl-raw-options="sub-format=ass/all,"

[youtube]
deband=yes
# deband-iterations=4
# deband-threshold=80
# deband-range=6
# deband-grain=85
profile-cond=p.path:lower():match("youtube") or p.path:lower():match("youtu.be")
profile-restore=copy
volume=60
ytdl-raw-options="playlist-reverse=,sub-format=ass/all,cookies-from-browser=firefox,mark-watched=,no-check-certificate="

# Protocol
[protocol.https]
cache-secs=9999
cache=yes
demuxer-max-back-bytes=1GiB
demuxer-max-bytes=2GiB
profile-restore=copy

[protocol.http]
profile-restore=copy
profile=protocol.https
