keep-open=yes
volume=60

[youtube]
profile-desc="profile for YouTube videos"
profile-cond=get("path",""):find('youtu%.?be')
deband=yes
ytdl-raw-options="mark-watched="
ytdl-format=bestvideo+bestaudio/best

[protocol.https]
demuxer-max-bytes=2GiB
demuxer-max-back-bytes=1GiB

[protocol.http]
profile=protocol.https
