exec-once=sh -c 'swaybg -i "$(cat ~/.cache/wal/wal 2>/dev/null || echo ~/walls/wall1.png)"'
exec-once=waybar

# Monitor
monitorrule=model:XG27AQDMG,width:2560,height:1440,refresh:239.972000

bind=SUPER,r,reload_config
bind=SUPER+SHIFT,e,quit
bind=SUPER,Return,spawn,foot
bind=SUPER,d,spawn,rofi -show drun

bind=SUPER,q,killclient

# Window state
bind=SUPER+SHIFT,Space,togglefloating
bind=SUPER,f,togglefullscreen

bind=SUPER,1,comboview,1
bind=SUPER,2,comboview,2
bind=SUPER,3,comboview,3
bind=SUPER,4,comboview,4
bind=SUPER,5,comboview,5
bind=SUPER,6,comboview,6
bind=SUPER,7,comboview,7
bind=SUPER,8,comboview,8
bind=SUPER,9,comboview,9

# Move client to tag
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

# Toggle tag view
bind=SUPER+CTRL,1,toggleview,1
bind=SUPER+CTRL,2,toggleview,2
bind=SUPER+CTRL,3,toggleview,3
bind=SUPER+CTRL,4,toggleview,4
bind=SUPER+CTRL,5,toggleview,5
bind=SUPER+CTRL,6,toggleview,6
bind=SUPER+CTRL,7,toggleview,7
bind=SUPER+CTRL,8,toggleview,8
bind=SUPER+CTRL,9,toggleview,9

bind=SUPER,j,focusstack,next
bind=SUPER,k,focusstack,prev

# DWM style binds
bind=SUPER,h,setmfact,-0.05
bind=SUPER,l,setmfact,+0.05
bind=SUPER,Space,zoom

# Layouts
bind=SUPER,t,setlayout,tile
bind=SUPER,m,setlayout,monocle
bind=SUPER,v,setlayout,vertical_grid
bind=SUPER+SHIFT,v,setlayout,vertical_scroller

animations = 0

# GAPS
gappih=8
gappiv=8
gappoh=8
gappov=8
borderpx=1

# Turn off silly defaults
new_is_master=0
enable_hotarea=0
axis_bind_apply_timeout=100
drag_tile_to_tile=1
enable_floating_snap=0
snap_distance=30

# KEEB
repeat_rate=35
repeat_delay=200
