player-operation-mode=pseudo-gui
keep-open=yes

[youtube]
profile-desc="profile for YouTube videos"
profile-cond=get("path",""):find('youtu%.?be')
deband=yes
volume=60
ytdl-raw-options="cookies-from-browser=firefox,mark-watched=,sub-langs=en.*,write-subs=,write-auto-subs="
ytdl-format=bestvideo[height<=?1440][fps<=?60][format_id!*=-sr]+bestaudio/bestvideo[height<=?1440][fps<=?60]+bestaudio/best

[protocol.https]
demuxer-max-bytes=2GiB
demuxer-max-back-bytes=1GiB

[protocol.http]
profile=protocol.https
