[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
opacity = 0.8
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.normal]
family = "ttf-jetbrains-mono-nerd"
style = "Regular"

[font.bold]
family = "ttf-jetbrains-mono-nerd"
style = "Bold"

[font.italic]
family = "ttf-jetbrains-mono-nerd"
style = "Italic"

[font.bold_italic]
family = "ttf-jetbrains-mono-nerd"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[general]
live_config_reload = true
